### ISSUE TITLE
filter raw npi data into searchable model for api endpoint

### ISSUE THREAD

**Issue by eddyizm** [eddyizm/NPI_FILES#29]
- decide what fields we want to search on and create a sub model for this. 
- ~~this probably needs to include some db indexing and optimization~~
- ~~return first 20 results max?~~

**Comment by eddyizm** [comment]
Added these fields to start the query on

```
    npi:
    provider_last_name_legal_name_field: 
    provider_first_name: 
    provider_business_mailing_address_state_name: 
    provider_business_mailing_address_postal_code
```
Did not put a limit yet. probably need to add another card for pagination etc.
